AllCops:
  Exclude:
    - 'audit_reports/**/*'
    - 'cache/**/*'
    - 'lambda/**/*'
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  # this is too overhwelming to even look at for now
  Enabled: false
Metrics/PerceivedComplexity:
  # this is too overhwelming to even look at for now
  Enabled: false
Metrics/AbcSize:
  # this is too overhwelming to even look at for now
  Enabled: false
Metrics/MethodLength:
  # this is too overhwelming to even look at for now
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
